export const USER_SVC_PORT_ENV = 'USER_SVC_PORT';
export const BUSINESS_SVC_PORT_ENV = 'BUSINESS_SVC_PORT';
export const ACCESS_TOKEN_EXPIRES_ENV = 'ACCESS_TOKEN_EXPIRES';
export const REFRESH_TOKEN_EXPIRES_ENV = 'REFRESH_TOKEN_EXPIRES';
